### ISSUE TITLE
No usable repository description.

### ISSUE THREAD

**Issue by vi** [steveklabnik/CLOSURE#3]
What is `CLOSURE.PDF`? Readme is not helpful. I don't even understand is it a scientific paper, a book, a program or a game. My first though was "Fed up! I'm closing! Here is my closure manifesto."

Along with `Thanks, _why.` there should be answer to `What is CLOSURE?` question in repository description.

**Comment by mikehenrty** [comment]
I think the problem is that nobody except for _why and perhaps a few people close to him know the context of this material. It just showed up on his blog one day after years of online radio silence. These hacker news posts show some of the confusion and excitement from that time:
https://news.ycombinator.com/item?id=5015087
https://news.ycombinator.com/item?id=5571387

Note that the link from Hacker News, _why's original blog, is now operated by some Australian guy with no apparent relation to _why.

**Comment by steveklabnik** [comment]
Works of art can be hard to understand, but that's okay. Given that this is an artifact, I'm going to leave it as-is.
